# Generated by Django 6.1 on 2026-08-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('total_beds', models.PositiveIntegerField(default=1)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
        ),
    ]
