# Generated by Django 6.1 on 2026-08-18 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('internet', 'Internet'), ('food', 'Food'), ('salaries', 'Salaries'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='hostel.hostel')),
            ],
        ),
    ]
